spring.application.name=virtualthreads

# =========================
# H2DB
# =========================

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# =========================
# Configure Hibernate DDL generation
# =========================

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# =========================
# API DOC
# =========================

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui-custom.html
springdoc.writer-with-default-pretty-printer=true
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
spring.main.allow-bean-definition-overriding=true
spring.mvc.problemdetails.enabled=true

# =========================
# Virtual Threads
# =========================

spring.threads.virtual.enabled=true

# =========================
# KAFKA
# =========================
spring.kafka.bootstrap-servers=localhost:9092
